### ISSUE TITLE
Links to online playground

### ISSUE THREAD

**Issue by jimthedev** [angular-class/awesome-angular2#14]
@gdi2290, what are the links to the Online Playground? Placeholders or an error?

**Comment by gdi2290** [comment]
They're meant for plunker/jsbin/jsfiddle links where someone can quickly jump in

**Comment by jimthedev** [comment]
cool. thanks.

**Comment by gdi2290** [comment]
ya feel free to include more subjects for better lists. If it's too crazy I'll just open a pull-request
