### ISSUE TITLE
fullstack-angular2-starter not available

### ISSUE THREAD

**Issue by tamascsaba** [angular-class/awesome-angular2#17]
https://github.com/angular-class/fullstack-angular2-starter - 404

**Comment by tamascsaba** [comment]
@gdi2290 ??

**Comment by gdi2290** [comment]
it will be out soon. The repo needs to be updated to latest changes

**Comment by tamascsaba** [comment]
@gdi2290 when you'll publicate?

**Comment by tamascsaba** [comment]
It is same that: https://github.com/angular-class/angular2-universal-starter?

**Comment by gdi2290** [comment]
we changed it last minute since people needed a simpler introduction to server rendering

**Comment by gdi2290** [comment]
I added the universal starter via https://github.com/angular-class/awesome-angular2/commit/e3dc1456678e27facfd065d6f5b71c63b521f9b6
