### ISSUE TITLE
Why did you remove `Features`?

### ISSUE THREAD

**Issue by splincode** [angular-class/awesome-angular2#298]
![image](https://user-images.githubusercontent.com/12021443/35470727-d3f8834a-035f-11e8-97ed-64a775da8603.png)

But some content left? You only needed 2 groups to update:

![image](https://user-images.githubusercontent.com/12021443/35470756-7651acb6-0360-11e8-9b1d-fe13bac0020a.png)

**Comment by PatrickJS** [comment]
can you update the readme? the links and descriptions were outdated
