### ISSUE TITLE
Build/PR Failed

### ISSUE THREAD

**Issue by gargrv** [angular-class/awesome-angular2#404]
As most of links are outdated, all PRs are getting failed.

**Comment by benwinding** [comment]
Seems to be to the [validate_urls.sh](https://github.com/PatrickJS/awesome-angular/blob/gh-pages/scripts/validate_urls.sh) file failing in the Travis CI builds.
Should we disable that? And might be easier to migrate to Github Actions too

**Comment by PatrickJS** [comment]
i fixed it
