### ISSUE TITLE
Is this repo abandoned? (I can help)

### ISSUE THREAD

**Issue by benwinding** [angular-class/awesome-angular2#405]
Hi @PatrickJS,
This seems to be the definitive _awesome-list_ for angular. Just wondering if you would like some help merging PR's and updating information? Let me know
Cheers,
Ben

**Comment by PatrickJS** [comment]
Yeah, plz help

**Comment by alujs** [comment]
Can you give us a list of all the things that are deprecated?

**Comment by JohnnyDevNull** [comment]
Well i could also help if you want. Would be nice to contribute to some angular community stuff.

**Comment by PatrickJS** [comment]
I added you guys anyone that helps feel free to add your github to the sponsor list for the repo
