### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by j-tesla** [angular-class/awesome-angular2#435]
In https://github.com/PatrickJS/awesome-angular#video-tutorials, [HiRez.io - Angular Basics](https://www.hirez.io/c/angular-basics-1/e/episode-1-course-overview) and [HiRez.io - Angular In Depth - Components](https://www.hirez.io/c/components-1/e/episode-1-course-overview) are not working.

**Comment by benwinding** [comment]
Hi @j-tesla,
If you find any broken links, please submit a PR to remove the items from the list.
Cheers,
Ben
